version: '3.8'

services:
  postgres:
    container_name: SurveyDB
    image: postgres
    environment:
      POSTGRES_DB: SurveyDB
      POSTGRES_USER: surveyuser
      POSTGRES_PASSWORD: surveypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U surveyuser -d SurveyDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: survey_postgres_data