spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:SurveyDB}
        username: ${DB_USER:surveyuser}
        password: ${DB_PASSWORD:surveypass}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: ${SHOW_SQL:false}
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false
        defer-datasource-initialization: true

# Admin user configuration
app:
    admin:
        username: ${ADMIN_USERNAME:admin}
        email: ${ADMIN_EMAIL:admin@survey.com}
        password: ${ADMIN_PASSWORD:admin123}
    jwt:
        secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
        expiration: ${JWT_EXPIRATION:86400000}

# Logging configuration
logging:
    level:
        org.hibernate.SQL: ${LOG_SQL:WARN}
        org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_SQL_PARAMS:WARN}
        com.darknessopirate.appvsurveyapi: ${LOG_APP:INFO}
        root: ${LOG_ROOT:INFO}

# Swagger/OpenAPI configuration
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method
        tags-sorter: alpha
    default-produces-media-type: application/json

# Server configuration
server:
    port: 8080