spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/SurveyDB
        username: surveyuser
        password: surveypass
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Keep this as update to preserve data between restarts
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false
        # allow data.sql to run after tables are created/updated
        defer-datasource-initialization: true

# Admin user configuration
app:
    admin:
        username: admin
        email: admin@survey.com
        password: admin123
    jwt:
        secret: mySecretKey123456789012345678901234567890
        expiration: 86400000 # 24 hours in milliseconds

# Logging configuration (keep as is)
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        com.darknessopirate.appvsurveyapi: DEBUG

# Swagger/OpenAPI configuration
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method & alpha
        tags-sorter: alpha

    default-produces-media-type: application/json